name: soundcloud_audio_player
description: SoundCloud Audio Player For Flutter.
publish_to: 'none'
version: 0.0.8+1

environment:
  sdk: ">=2.12.0-133.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.17.2
  built_collection: ^5.0.0-nullsafety.0
  built_value: ^8.0.0-nullsafety.0
  flutter_bloc: ^4.0.1

dev_dependencies:
  build_runner: ^1.11.0
  built_value_generator: ^8.0.0-nullsafety.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/tunes.json
