name: audio
description: SoundCloud Audio Player for Flutter.

version: 0.0.8+1

environment:
  sdk: ">=2.12.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.18.3
  built_collection: ^5.0.0
  built_value: ^8.0.4
  flutter_bloc: ^7.0.0

dev_dependencies:
  #build_runner: ^2.0.0
  built_value_generator: ^8.0.4
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/tunes.json
