name: soundcloud_audio_player
description: SoundCloud Audio Player For Flutter.
publish_to: 'none'
version: 0.0.8+1

environment:
  sdk: ">=2.10.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^0.17.2
  built_collection: ^4.3.2
  built_value: ^7.1.0
  flutter_bloc: ^4.0.1

dev_dependencies:
  build_runner: ^1.8.1
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/data/tunes.json
