name: CI

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          channel: "beta"

      - name: Install dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed lib test example

      - name: Analyzing project
        run: flutter analyze